### ISSUE TITLE
.sizeOf() is reporting inconsistent results!

### ISSUE THREAD

**Issue by lujianzhao** [wobuaihuangjun/DatabaseManager#3]
使用时，有些时候会报错java.lang.IllegalStateException: DbCache$1.sizeOf() is reporting inconsistent results!
在 mLruCache.put(tableName, tableCache);时报错。
解决办法：
mLruCache = new LruCache<String, Map<String, String>>(CACHE_SIZE) {
            @Override
            protected int sizeOf(String key, Map<String, String> value) {
                // 此处计算内存占用比较麻烦，所以使用了条数作为缓存限制
                // 如果大家有好的建议欢迎提出
                return Check.isEmpty(value) ? 0 : value.size();
            }
        };

**Comment by wobuaihuangjun** [comment]
@lujianzhao 这块确实有问题，也没有细想过。感觉数据库查询的缓存没什么太大作用，已经去掉了。
