### ISSUE TITLE
OrmLiteDao的private int updateIfValueNotNull(T t)有BUG

### ISSUE THREAD

**Issue by lujianzhao** [wobuaihuangjun/DatabaseManager#4]
当更新的对象是从数据库中取出的数据时，就会报错。字段会多了"CREATOR" 和"serialVersionUID"。
请问除了忽略外，还有什么更好的办法呢？

**Comment by wobuaihuangjun** [comment]
@lujianzhao 我测试试没有你这个问题的，不过项目中曾经出现过你说的这个问题，是由于定义的bean不是一个javabean，能发下你数据Bean吗？

**Comment by lujianzhao** [comment]
@wobuaihuangjun 可能是因为我的bean里面没有写serialVersionUID导致的。
当Bean实现了Serializable和Parcelable后，就会多出这两个字段。

解决办法：在setObjectValueIfNotNull(T t, Object obj)和getFieldsIfValueNotNull(Object obj)方法中增加一个判断就可以解决该问题了，考虑到采用的是ormLite数据库，所以只需要解析DatabaseField注解的字段，其余字段忽略。

**Comment by lujianzhao** [comment]
在下面的两个方法中增加一个判断就可以解决该问题了，考虑到采用的是ormLite数据库，所以只需要解析DatabaseField注解的字段，其余字段忽略。

/**
     * 过滤数据实体中DatabaseField注解的字段值为null的字段
     *
     * @param t   过滤后不包含null字段的数据
     * @param obj 被过滤的数据
     * @throws IllegalAccessException
     * @throws NoSuchFieldException
     */
    private void setObjectValueIfNotNull(T t, Object obj) throws IllegalAccessException, NoSuchFieldException {
        Field[] fields = obj.getClass().getDeclaredFields();
        Class<?> cls = t.getClass();
        for (Field field : fields) {
            DatabaseField annotation = field.getAnnotation(DatabaseField.class);
            if (annotation == null) {
                continue;
            }
            field.setAccessible(true);
            if (field.getName().equals("id")) {
                continue;
            }
            Object valueObj = field.get(obj);
            if (valueObj != null) {
                Field f = cls.getDeclaredField(field.getName());
                if (f != null) {
                    f.setAccessible(true);
                    f.set(t, valueObj);
                } else {
                    LogUtils.e( "no this field:" + field.getName());
                }
            }
        }
    }

    /**
     * 获取对象DatabaseField注解的属性值不为空的属性名称和属性值
     *
     * @param obj 数据实体对象
     * @return 属性名称和属性值键值对集合
     */
    private Map<String, Object> getFieldsIfValueNotNull(Object obj) {
        Map<String, Object> map = new HashMap<>();
        Field[] fields = obj.getClass().getDeclaredFields();
        for (Field field : fields) {
            DatabaseField annotation = field.getAnnotation(DatabaseField.class);
            if (annotation == null) {
                continue;
            }

            field.setAccessible(true);
            Object valueObj = null;
            try {
                valueObj = field.get(obj);
            } catch (IllegalAccessException e) {
                LogUtils.e(e);
            }
            if (valueObj != null) {
                map.put(field.getName(), valueObj);
            }
        }
        return map;
    }

**Comment by wobuaihuangjun** [comment]
@lujianzhao 已添加注解过滤
